# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # 在push或pull_request请求事件上触发workflow，但仅适用于主分支
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps表示将作为job一部分执行的任务序列
    steps:
      # 在$GITHUB_WORKSPACE下检查您的存储库，以便您的job可以访问它
      - uses: actions/checkout@v3

      - name: Setup Hexo Dependencies
        run: |
          npm install hexo-cli -g
          npm install        

      - name: Setup Deploy Private Key
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Git Infomation
        run: |
          git config --global user.name 'jaw52' 
          git config --global user.email '2135326728@qq.com'
      - name: Deploy Hexo
        run: |
          hexo clean
          hexo deploy
